// 300+ integrations organized by category — no emojis, no icons except brand logos
// Each integration maps to a Composio app ID for real OAuth connection

export interface Integration {
  id: string;
  name: string;
  description: string;
  category: string;
  app: string; // Composio app ID
}

export const INTEGRATION_CATEGORIES = [
  "All",
  "Communication",
  "Productivity",
  "Development",
  "Storage & Files",
  "Design",
  "CRM & Sales",
  "Project Management",
] as const;

// Curated top 15 essential integrations
export const integrations: Integration[] = [
  { id: "gmail", name: "Gmail", description: "Send, read and manage emails", category: "Communication", app: "gmail" },
  { id: "gcalendar", name: "Google Calendar", description: "Events and scheduling", category: "Productivity", app: "googlecalendar" },
  { id: "gdrive", name: "Google Drive", description: "Cloud file storage", category: "Storage & Files", app: "googledrive" },
  { id: "google-sheets", name: "Google Sheets", description: "Online spreadsheets", category: "Productivity", app: "googlesheets" },
  { id: "slack", name: "Slack", description: "Team messaging and channels", category: "Communication", app: "slack" },
  { id: "notion", name: "Notion", description: "Notes, docs, and wikis", category: "Productivity", app: "notion" },
  { id: "github", name: "GitHub", description: "Code hosting and collaboration", category: "Development", app: "github" },
  { id: "linear", name: "Linear", description: "Issue tracking for teams", category: "Project Management", app: "linear" },
  { id: "figma", name: "Figma", description: "Collaborative design", category: "Design", app: "figma" },
  { id: "discord", name: "Discord", description: "Community servers and messaging", category: "Communication", app: "discord" },
  { id: "trello", name: "Trello", description: "Visual project boards", category: "Project Management", app: "trello" },
  { id: "asana", name: "Asana", description: "Work management for teams", category: "Project Management", app: "asana" },
  { id: "dropbox", name: "Dropbox", description: "File sync and sharing", category: "Storage & Files", app: "dropbox" },
  { id: "hubspot", name: "HubSpot", description: "CRM for sales and marketing", category: "CRM & Sales", app: "hubspot" },
  { id: "airtable", name: "Airtable", description: "Spreadsheet-database hybrid", category: "Productivity", app: "airtable" },
];

// Legacy entries kept below are intentionally unused — file truncated above.
const _legacyUnused: Integration[] = [
  // Communication
  { id: "gmail", name: "Gmail", description: "Send, read and manage emails", category: "Communication", app: "gmail" },
  { id: "outlook", name: "Outlook", description: "Microsoft email and calendar", category: "Communication", app: "outlook" },
  { id: "slack", name: "Slack", description: "Team messaging and channels", category: "Communication", app: "slack" },
  { id: "discord", name: "Discord", description: "Community servers and messaging", category: "Communication", app: "discord" },
  { id: "teams", name: "Microsoft Teams", description: "Team collaboration and meetings", category: "Communication", app: "microsoftteams" },
  { id: "zoom", name: "Zoom", description: "Video conferencing and webinars", category: "Communication", app: "zoom" },
  { id: "telegram", name: "Telegram", description: "Messaging and bot automation", category: "Communication", app: "telegram" },
  { id: "whatsapp", name: "WhatsApp Business", description: "Customer messaging at scale", category: "Communication", app: "whatsapp" },
  { id: "twilio", name: "Twilio", description: "SMS, voice, and messaging APIs", category: "Communication", app: "twilio" },
  { id: "sendgrid", name: "SendGrid", description: "Transactional email delivery", category: "Communication", app: "sendgrid" },
  { id: "mailchimp", name: "Mailchimp", description: "Email campaigns and automation", category: "Communication", app: "mailchimp" },
  { id: "intercom", name: "Intercom", description: "Customer messaging platform", category: "Communication", app: "intercom" },
  { id: "webex", name: "Webex", description: "Video meetings and collaboration", category: "Communication", app: "webex" },
  { id: "ringcentral", name: "RingCentral", description: "Cloud phone and messaging", category: "Communication", app: "ringcentral" },
  { id: "vonage", name: "Vonage", description: "Communication APIs", category: "Communication", app: "vonage" },

  // Productivity
  { id: "notion", name: "Notion", description: "Notes, docs, and wikis", category: "Productivity", app: "notion" },
  { id: "gcalendar", name: "Google Calendar", description: "Events and scheduling", category: "Productivity", app: "googlecalendar" },
  { id: "todoist", name: "Todoist", description: "Task management", category: "Productivity", app: "todoist" },
  { id: "evernote", name: "Evernote", description: "Note-taking and organization", category: "Productivity", app: "evernote" },
  { id: "onenote", name: "OneNote", description: "Microsoft digital notebook", category: "Productivity", app: "onenote" },
  { id: "airtable", name: "Airtable", description: "Spreadsheet-database hybrid", category: "Productivity", app: "airtable" },
  { id: "google-sheets", name: "Google Sheets", description: "Online spreadsheets", category: "Productivity", app: "googlesheets" },
  { id: "google-docs", name: "Google Docs", description: "Collaborative documents", category: "Productivity", app: "googledocs" },
  { id: "google-forms", name: "Google Forms", description: "Surveys and forms", category: "Productivity", app: "googleforms" },
  { id: "typeform", name: "Typeform", description: "Beautiful forms and surveys", category: "Productivity", app: "typeform" },
  { id: "calendly", name: "Calendly", description: "Meeting scheduling", category: "Productivity", app: "calendly" },
  { id: "coda", name: "Coda", description: "All-in-one documents", category: "Productivity", app: "coda" },
  { id: "clickup", name: "ClickUp", description: "Tasks, docs, goals", category: "Productivity", app: "clickup" },
  { id: "microsoft-todo", name: "Microsoft To Do", description: "Personal task manager", category: "Productivity", app: "microsofttodo" },
  { id: "bear", name: "Bear", description: "Markdown notes", category: "Productivity", app: "bear" },

  // Development
  { id: "github", name: "GitHub", description: "Code hosting and collaboration", category: "Development", app: "github" },
  { id: "gitlab", name: "GitLab", description: "DevOps platform", category: "Development", app: "gitlab" },
  { id: "bitbucket", name: "Bitbucket", description: "Git code management", category: "Development", app: "bitbucket" },
  { id: "vercel", name: "Vercel", description: "Frontend deployment", category: "Development", app: "vercel" },
  { id: "netlify", name: "Netlify", description: "Web hosting and deployment", category: "Development", app: "netlify" },
  { id: "heroku", name: "Heroku", description: "Cloud application platform", category: "Development", app: "heroku" },
  { id: "figma", name: "Figma", description: "Design and prototyping", category: "Development", app: "figma" },
  { id: "linear", name: "Linear", description: "Issue tracking for teams", category: "Development", app: "linear" },
  { id: "jira", name: "Jira", description: "Agile project management", category: "Development", app: "jira" },
  { id: "sentry", name: "Sentry", description: "Error tracking and monitoring", category: "Development", app: "sentry" },
  { id: "postman", name: "Postman", description: "API development platform", category: "Development", app: "postman" },
  { id: "npm", name: "npm", description: "Package management", category: "Development", app: "npm" },
  { id: "docker", name: "Docker Hub", description: "Container registry", category: "Development", app: "dockerhub" },
  { id: "stackoverflow", name: "Stack Overflow", description: "Developer Q&A", category: "Development", app: "stackoverflow" },
  { id: "codepen", name: "CodePen", description: "Frontend code playground", category: "Development", app: "codepen" },
  { id: "replit", name: "Replit", description: "Online IDE", category: "Development", app: "replit" },
  { id: "render", name: "Render", description: "Cloud hosting platform", category: "Development", app: "render" },
  { id: "railway", name: "Railway", description: "Infrastructure platform", category: "Development", app: "railway" },
  { id: "supabase", name: "Supabase", description: "Backend as a service", category: "Development", app: "supabase" },
  { id: "firebase", name: "Firebase", description: "Google app platform", category: "Development", app: "firebase" },

  // CRM & Sales
  { id: "hubspot", name: "HubSpot", description: "CRM, marketing, and sales", category: "CRM & Sales", app: "hubspot" },
  { id: "salesforce", name: "Salesforce", description: "Enterprise CRM platform", category: "CRM & Sales", app: "salesforce" },
  { id: "pipedrive", name: "Pipedrive", description: "Sales pipeline management", category: "CRM & Sales", app: "pipedrive" },
  { id: "zoho-crm", name: "Zoho CRM", description: "Customer relationship management", category: "CRM & Sales", app: "zohocrm" },
  { id: "freshsales", name: "Freshsales", description: "Sales CRM by Freshworks", category: "CRM & Sales", app: "freshsales" },
  { id: "close", name: "Close", description: "Inside sales CRM", category: "CRM & Sales", app: "close" },
  { id: "copper", name: "Copper", description: "CRM for Google Workspace", category: "CRM & Sales", app: "copper" },
  { id: "apollo", name: "Apollo.io", description: "Sales intelligence and engagement", category: "CRM & Sales", app: "apollo" },
  { id: "lemlist", name: "Lemlist", description: "Cold email outreach", category: "CRM & Sales", app: "lemlist" },
  { id: "instantly", name: "Instantly", description: "Email outreach platform", category: "CRM & Sales", app: "instantly" },
  { id: "outreach", name: "Outreach", description: "Sales execution platform", category: "CRM & Sales", app: "outreach" },
  { id: "gong", name: "Gong", description: "Revenue intelligence", category: "CRM & Sales", app: "gong" },
  { id: "clearbit", name: "Clearbit", description: "Business intelligence", category: "CRM & Sales", app: "clearbit" },
  { id: "zoominfo", name: "ZoomInfo", description: "B2B data platform", category: "CRM & Sales", app: "zoominfo" },

  // Marketing
  { id: "google-ads", name: "Google Ads", description: "Search and display advertising", category: "Marketing", app: "googleads" },
  { id: "facebook-ads", name: "Meta Ads", description: "Facebook and Instagram ads", category: "Marketing", app: "facebookads" },
  { id: "tiktok-ads", name: "TikTok Ads", description: "Short-form video advertising", category: "Marketing", app: "tiktokads" },
  { id: "linkedin-ads", name: "LinkedIn Ads", description: "B2B advertising", category: "Marketing", app: "linkedinads" },
  { id: "activecampaign", name: "ActiveCampaign", description: "Email and marketing automation", category: "Marketing", app: "activecampaign" },
  { id: "convertkit", name: "ConvertKit", description: "Creator email marketing", category: "Marketing", app: "convertkit" },
  { id: "drip", name: "Drip", description: "E-commerce email marketing", category: "Marketing", app: "drip" },
  { id: "brevo", name: "Brevo", description: "Marketing platform", category: "Marketing", app: "brevo" },
  { id: "klaviyo", name: "Klaviyo", description: "E-commerce marketing", category: "Marketing", app: "klaviyo" },
  { id: "semrush", name: "Semrush", description: "SEO and marketing toolkit", category: "Marketing", app: "semrush" },
  { id: "ahrefs", name: "Ahrefs", description: "SEO tools and backlinks", category: "Marketing", app: "ahrefs" },
  { id: "moz", name: "Moz", description: "SEO software", category: "Marketing", app: "moz" },
  { id: "buffer", name: "Buffer", description: "Social media scheduling", category: "Marketing", app: "buffer" },
  { id: "hootsuite", name: "Hootsuite", description: "Social media management", category: "Marketing", app: "hootsuite" },
  { id: "later", name: "Later", description: "Visual social media planner", category: "Marketing", app: "later" },
  { id: "unbounce", name: "Unbounce", description: "Landing page builder", category: "Marketing", app: "unbounce" },
  { id: "hotjar", name: "Hotjar", description: "Heatmaps and recordings", category: "Marketing", app: "hotjar" },

  // Social Media
  { id: "youtube", name: "YouTube", description: "Video content platform", category: "Social Media", app: "youtube" },
  { id: "instagram", name: "Instagram", description: "Photos, stories, and reels", category: "Social Media", app: "instagram" },
  { id: "facebook", name: "Facebook", description: "Social networking and pages", category: "Social Media", app: "facebook" },
  { id: "linkedin", name: "LinkedIn", description: "Professional networking", category: "Social Media", app: "linkedin" },
  { id: "tiktok", name: "TikTok", description: "Short-form video platform", category: "Social Media", app: "tiktok" },
  { id: "twitter", name: "X (Twitter)", description: "Microblogging and news", category: "Social Media", app: "twitter" },
  { id: "reddit", name: "Reddit", description: "Community discussions", category: "Social Media", app: "reddit" },
  { id: "pinterest", name: "Pinterest", description: "Visual discovery platform", category: "Social Media", app: "pinterest" },
  { id: "snapchat", name: "Snapchat", description: "Visual messaging", category: "Social Media", app: "snapchat" },
  { id: "tumblr", name: "Tumblr", description: "Blogging platform", category: "Social Media", app: "tumblr" },
  { id: "mastodon", name: "Mastodon", description: "Decentralized social network", category: "Social Media", app: "mastodon" },
  { id: "threads", name: "Threads", description: "Text-based social network", category: "Social Media", app: "threads" },
  { id: "bluesky", name: "Bluesky", description: "Decentralized social media", category: "Social Media", app: "bluesky" },

  // Storage & Files
  { id: "gdrive", name: "Google Drive", description: "Cloud file storage", category: "Storage & Files", app: "googledrive" },
  { id: "onedrive", name: "OneDrive", description: "Microsoft cloud storage", category: "Storage & Files", app: "onedrive" },
  { id: "dropbox", name: "Dropbox", description: "File hosting and sync", category: "Storage & Files", app: "dropbox" },
  { id: "box", name: "Box", description: "Enterprise cloud storage", category: "Storage & Files", app: "box" },
  { id: "aws-s3", name: "AWS S3", description: "Object storage service", category: "Storage & Files", app: "awss3" },
  { id: "google-cloud-storage", name: "Google Cloud Storage", description: "GCP object storage", category: "Storage & Files", app: "googlecloudstorage" },
  { id: "azure-blob", name: "Azure Blob Storage", description: "Microsoft cloud storage", category: "Storage & Files", app: "azureblobstorage" },
  { id: "wasabi", name: "Wasabi", description: "Hot cloud storage", category: "Storage & Files", app: "wasabi" },
  { id: "backblaze", name: "Backblaze B2", description: "Affordable cloud storage", category: "Storage & Files", app: "backblaze" },
  { id: "sharepoint", name: "SharePoint", description: "Enterprise content management", category: "Storage & Files", app: "sharepoint" },

  // Finance
  { id: "stripe", name: "Stripe", description: "Payment processing", category: "Finance", app: "stripe" },
  { id: "paypal", name: "PayPal", description: "Online payments", category: "Finance", app: "paypal" },
  { id: "quickbooks", name: "QuickBooks", description: "Accounting software", category: "Finance", app: "quickbooks" },
  { id: "xero", name: "Xero", description: "Cloud accounting", category: "Finance", app: "xero" },
  { id: "freshbooks", name: "FreshBooks", description: "Invoicing and accounting", category: "Finance", app: "freshbooks" },
  { id: "wave", name: "Wave", description: "Free accounting software", category: "Finance", app: "wave" },
  { id: "square", name: "Square", description: "Point of sale and payments", category: "Finance", app: "square" },
  { id: "wise", name: "Wise", description: "International money transfers", category: "Finance", app: "wise" },
  { id: "plaid", name: "Plaid", description: "Financial data connectivity", category: "Finance", app: "plaid" },
  { id: "brex", name: "Brex", description: "Corporate credit cards", category: "Finance", app: "brex" },
  { id: "chargebee", name: "Chargebee", description: "Subscription billing", category: "Finance", app: "chargebee" },
  { id: "paddle", name: "Paddle", description: "SaaS billing platform", category: "Finance", app: "paddle" },
  { id: "lemon-squeezy", name: "Lemon Squeezy", description: "Digital product payments", category: "Finance", app: "lemonsqueezy" },

  // Design
  { id: "canva", name: "Canva", description: "Graphic design platform", category: "Design", app: "canva" },
  { id: "adobe-cc", name: "Adobe Creative Cloud", description: "Design and creative tools", category: "Design", app: "adobecreativecloud" },
  { id: "sketch", name: "Sketch", description: "Digital design toolkit", category: "Design", app: "sketch" },
  { id: "invision", name: "InVision", description: "Digital product design", category: "Design", app: "invision" },
  { id: "zeplin", name: "Zeplin", description: "Design handoff platform", category: "Design", app: "zeplin" },
  { id: "miro", name: "Miro", description: "Online whiteboard", category: "Design", app: "miro" },
  { id: "whimsical", name: "Whimsical", description: "Flowcharts and wireframes", category: "Design", app: "whimsical" },
  { id: "framer", name: "Framer", description: "Interactive design tool", category: "Design", app: "framer" },
  { id: "spline", name: "Spline", description: "3D design tool", category: "Design", app: "spline" },
  { id: "lottiefiles", name: "LottieFiles", description: "Animation platform", category: "Design", app: "lottiefiles" },
  { id: "dribbble", name: "Dribbble", description: "Design community", category: "Design", app: "dribbble" },
  { id: "behance", name: "Behance", description: "Creative portfolio showcase", category: "Design", app: "behance" },

  // Analytics
  { id: "google-analytics", name: "Google Analytics", description: "Web analytics service", category: "Analytics", app: "googleanalytics" },
  { id: "mixpanel", name: "Mixpanel", description: "Product analytics", category: "Analytics", app: "mixpanel" },
  { id: "amplitude", name: "Amplitude", description: "Product intelligence", category: "Analytics", app: "amplitude" },
  { id: "segment", name: "Segment", description: "Customer data platform", category: "Analytics", app: "segment" },
  { id: "posthog", name: "PostHog", description: "Open-source product analytics", category: "Analytics", app: "posthog" },
  { id: "plausible", name: "Plausible", description: "Privacy-friendly analytics", category: "Analytics", app: "plausible" },
  { id: "datadog", name: "Datadog", description: "Cloud monitoring", category: "Analytics", app: "datadog" },
  { id: "new-relic", name: "New Relic", description: "Observability platform", category: "Analytics", app: "newrelic" },
  { id: "looker", name: "Looker", description: "Business intelligence", category: "Analytics", app: "looker" },
  { id: "tableau", name: "Tableau", description: "Data visualization", category: "Analytics", app: "tableau" },
  { id: "metabase", name: "Metabase", description: "Open-source BI tool", category: "Analytics", app: "metabase" },
  { id: "heap", name: "Heap", description: "Digital insights platform", category: "Analytics", app: "heap" },

  // Project Management
  { id: "asana", name: "Asana", description: "Work management platform", category: "Project Management", app: "asana" },
  { id: "trello", name: "Trello", description: "Kanban-style boards", category: "Project Management", app: "trello" },
  { id: "monday", name: "Monday.com", description: "Work operating system", category: "Project Management", app: "monday" },
  { id: "basecamp", name: "Basecamp", description: "Project management", category: "Project Management", app: "basecamp" },
  { id: "wrike", name: "Wrike", description: "Collaborative work management", category: "Project Management", app: "wrike" },
  { id: "smartsheet", name: "Smartsheet", description: "Dynamic work platform", category: "Project Management", app: "smartsheet" },
  { id: "teamwork", name: "Teamwork", description: "Client work management", category: "Project Management", app: "teamwork" },
  { id: "shortcut", name: "Shortcut", description: "Software project management", category: "Project Management", app: "shortcut" },
  { id: "height", name: "Height", description: "Autonomous project tracker", category: "Project Management", app: "height" },
  { id: "notion-pm", name: "Notion Projects", description: "All-in-one workspace", category: "Project Management", app: "notionprojects" },

  // Customer Support
  { id: "zendesk", name: "Zendesk", description: "Customer service platform", category: "Customer Support", app: "zendesk" },
  { id: "freshdesk", name: "Freshdesk", description: "Help desk software", category: "Customer Support", app: "freshdesk" },
  { id: "helpscout", name: "Help Scout", description: "Customer communication", category: "Customer Support", app: "helpscout" },
  { id: "crisp", name: "Crisp", description: "All-in-one messaging", category: "Customer Support", app: "crisp" },
  { id: "drift", name: "Drift", description: "Conversational marketing", category: "Customer Support", app: "drift" },
  { id: "tawk", name: "Tawk.to", description: "Free live chat", category: "Customer Support", app: "tawkto" },
  { id: "front", name: "Front", description: "Shared inbox platform", category: "Customer Support", app: "front" },
  { id: "groove", name: "Groove", description: "Simple help desk", category: "Customer Support", app: "groove" },
  { id: "livechat", name: "LiveChat", description: "Customer service chat", category: "Customer Support", app: "livechat" },
  { id: "kayako", name: "Kayako", description: "Unified customer service", category: "Customer Support", app: "kayako" },

  // HR & Recruiting
  { id: "bamboohr", name: "BambooHR", description: "HR management software", category: "HR & Recruiting", app: "bamboohr" },
  { id: "gusto", name: "Gusto", description: "Payroll and benefits", category: "HR & Recruiting", app: "gusto" },
  { id: "workday", name: "Workday", description: "Enterprise HR platform", category: "HR & Recruiting", app: "workday" },
  { id: "greenhouse", name: "Greenhouse", description: "Recruiting software", category: "HR & Recruiting", app: "greenhouse" },
  { id: "lever", name: "Lever", description: "Talent acquisition", category: "HR & Recruiting", app: "lever" },
  { id: "deel", name: "Deel", description: "Global payroll and HR", category: "HR & Recruiting", app: "deel" },
  { id: "rippling", name: "Rippling", description: "Workforce platform", category: "HR & Recruiting", app: "rippling" },
  { id: "personio", name: "Personio", description: "HR software for SMEs", category: "HR & Recruiting", app: "personio" },
  { id: "lattice", name: "Lattice", description: "People management", category: "HR & Recruiting", app: "lattice" },
  { id: "ashby", name: "Ashby", description: "All-in-one recruiting", category: "HR & Recruiting", app: "ashby" },

  // E-commerce
  { id: "shopify", name: "Shopify", description: "E-commerce platform", category: "E-commerce", app: "shopify" },
  { id: "woocommerce", name: "WooCommerce", description: "WordPress e-commerce", category: "E-commerce", app: "woocommerce" },
  { id: "bigcommerce", name: "BigCommerce", description: "Enterprise e-commerce", category: "E-commerce", app: "bigcommerce" },
  { id: "magento", name: "Adobe Commerce", description: "Enterprise e-commerce", category: "E-commerce", app: "magento" },
  { id: "etsy", name: "Etsy", description: "Handmade marketplace", category: "E-commerce", app: "etsy" },
  { id: "amazon-seller", name: "Amazon Seller", description: "Marketplace selling", category: "E-commerce", app: "amazonseller" },
  { id: "ebay", name: "eBay", description: "Online marketplace", category: "E-commerce", app: "ebay" },
  { id: "gumroad", name: "Gumroad", description: "Digital product sales", category: "E-commerce", app: "gumroad" },
  { id: "salla", name: "Salla", description: "Arabic e-commerce platform", category: "E-commerce", app: "salla" },
  { id: "zid", name: "Zid", description: "Arabic e-commerce platform", category: "E-commerce", app: "zid" },
  { id: "printful", name: "Printful", description: "Print on demand", category: "E-commerce", app: "printful" },
  { id: "oberlo", name: "Oberlo", description: "Dropshipping marketplace", category: "E-commerce", app: "oberlo" },

  // AI & ML
  { id: "openai", name: "OpenAI", description: "GPT and AI models", category: "AI & ML", app: "openai" },
  { id: "anthropic", name: "Anthropic", description: "Claude AI models", category: "AI & ML", app: "anthropic" },
  { id: "google-ai", name: "Google AI", description: "Gemini and AI services", category: "AI & ML", app: "googleai" },
  { id: "replicate", name: "Replicate", description: "Run ML models", category: "AI & ML", app: "replicate" },
  { id: "huggingface", name: "Hugging Face", description: "ML model hub", category: "AI & ML", app: "huggingface" },
  { id: "stability-ai", name: "Stability AI", description: "Generative AI models", category: "AI & ML", app: "stabilityai" },
  { id: "elevenlabs", name: "ElevenLabs", description: "AI voice generation", category: "AI & ML", app: "elevenlabs" },
  { id: "deepgram", name: "Deepgram", description: "Speech recognition API", category: "AI & ML", app: "deepgram" },
  { id: "cohere", name: "Cohere", description: "Enterprise AI platform", category: "AI & ML", app: "cohere" },
  { id: "perplexity", name: "Perplexity", description: "AI-powered search", category: "AI & ML", app: "perplexity" },
  { id: "midjourney", name: "Midjourney", description: "AI image generation", category: "AI & ML", app: "midjourney" },
  { id: "runway", name: "Runway", description: "AI video generation", category: "AI & ML", app: "runway" },

  // Security
  { id: "onepassword", name: "1Password", description: "Password management", category: "Security", app: "onepassword" },
  { id: "lastpass", name: "LastPass", description: "Password vault", category: "Security", app: "lastpass" },
  { id: "okta", name: "Okta", description: "Identity management", category: "Security", app: "okta" },
  { id: "auth0", name: "Auth0", description: "Authentication platform", category: "Security", app: "auth0" },
  { id: "crowdstrike", name: "CrowdStrike", description: "Endpoint security", category: "Security", app: "crowdstrike" },
  { id: "snyk", name: "Snyk", description: "Developer security", category: "Security", app: "snyk" },
  { id: "hashicorp-vault", name: "HashiCorp Vault", description: "Secrets management", category: "Security", app: "hashicorpvault" },
  { id: "cloudflare", name: "Cloudflare", description: "Web security and CDN", category: "Security", app: "cloudflare" },

  // Database
  { id: "mongodb", name: "MongoDB", description: "NoSQL database", category: "Database", app: "mongodb" },
  { id: "postgresql", name: "PostgreSQL", description: "Relational database", category: "Database", app: "postgresql" },
  { id: "mysql", name: "MySQL", description: "Open-source database", category: "Database", app: "mysql" },
  { id: "redis", name: "Redis", description: "In-memory data store", category: "Database", app: "redis" },
  { id: "elastic", name: "Elasticsearch", description: "Search and analytics engine", category: "Database", app: "elasticsearch" },
  { id: "fauna", name: "Fauna", description: "Serverless database", category: "Database", app: "fauna" },
  { id: "planetscale", name: "PlanetScale", description: "MySQL-compatible serverless", category: "Database", app: "planetscale" },
  { id: "neon", name: "Neon", description: "Serverless Postgres", category: "Database", app: "neon" },
  { id: "upstash", name: "Upstash", description: "Serverless Redis and Kafka", category: "Database", app: "upstash" },
  { id: "cockroachdb", name: "CockroachDB", description: "Distributed SQL database", category: "Database", app: "cockroachdb" },

  // DevOps
  { id: "aws", name: "AWS", description: "Amazon cloud services", category: "DevOps", app: "aws" },
  { id: "gcp", name: "Google Cloud", description: "Google cloud platform", category: "DevOps", app: "googlecloud" },
  { id: "azure", name: "Microsoft Azure", description: "Microsoft cloud services", category: "DevOps", app: "azure" },
  { id: "digitalocean", name: "DigitalOcean", description: "Cloud infrastructure", category: "DevOps", app: "digitalocean" },
  { id: "terraform", name: "Terraform", description: "Infrastructure as code", category: "DevOps", app: "terraform" },
  { id: "kubernetes", name: "Kubernetes", description: "Container orchestration", category: "DevOps", app: "kubernetes" },
  { id: "jenkins", name: "Jenkins", description: "CI/CD automation", category: "DevOps", app: "jenkins" },
  { id: "circleci", name: "CircleCI", description: "Continuous integration", category: "DevOps", app: "circleci" },
  { id: "github-actions", name: "GitHub Actions", description: "CI/CD workflows", category: "DevOps", app: "githubactions" },
  { id: "pagerduty", name: "PagerDuty", description: "Incident management", category: "DevOps", app: "pagerduty" },
  { id: "opsgenie", name: "Opsgenie", description: "Alert management", category: "DevOps", app: "opsgenie" },
  { id: "grafana", name: "Grafana", description: "Monitoring dashboards", category: "DevOps", app: "grafana" },
  { id: "prometheus", name: "Prometheus", description: "Monitoring system", category: "DevOps", app: "prometheus" },
  { id: "fly-io", name: "Fly.io", description: "Global app deployment", category: "DevOps", app: "flyio" },

  // Education
  { id: "google-classroom", name: "Google Classroom", description: "Educational platform", category: "Education", app: "googleclassroom" },
  { id: "canvas", name: "Canvas LMS", description: "Learning management", category: "Education", app: "canvaslms" },
  { id: "coursera", name: "Coursera", description: "Online learning", category: "Education", app: "coursera" },
  { id: "udemy", name: "Udemy", description: "Online courses", category: "Education", app: "udemy" },
  { id: "teachable", name: "Teachable", description: "Course creation platform", category: "Education", app: "teachable" },
  { id: "loom", name: "Loom", description: "Video messaging", category: "Education", app: "loom" },
  { id: "moodle", name: "Moodle", description: "Open-source LMS", category: "Education", app: "moodle" },
  { id: "duolingo", name: "Duolingo", description: "Language learning", category: "Education", app: "duolingo" },

  // Legal
  { id: "docusign", name: "DocuSign", description: "Electronic signatures", category: "Legal", app: "docusign" },
  { id: "pandadoc", name: "PandaDoc", description: "Document workflow", category: "Legal", app: "pandadoc" },
  { id: "hellosign", name: "HelloSign", description: "E-signature solution", category: "Legal", app: "hellosign" },
  { id: "clio", name: "Clio", description: "Legal practice management", category: "Legal", app: "clio" },
  { id: "contractbook", name: "Contractbook", description: "Contract management", category: "Legal", app: "contractbook" },

  // Video & Media
  { id: "vimeo", name: "Vimeo", description: "Video hosting platform", category: "Video & Media", app: "vimeo" },
  { id: "wistia", name: "Wistia", description: "Video marketing", category: "Video & Media", app: "wistia" },
  { id: "streamyard", name: "StreamYard", description: "Live streaming studio", category: "Video & Media", app: "streamyard" },
  { id: "cloudinary", name: "Cloudinary", description: "Media management", category: "Video & Media", app: "cloudinary" },
  { id: "spotify", name: "Spotify", description: "Music and podcast platform", category: "Video & Media", app: "spotify" },
  { id: "soundcloud", name: "SoundCloud", description: "Audio sharing platform", category: "Video & Media", app: "soundcloud" },
  { id: "twitch", name: "Twitch", description: "Live streaming platform", category: "Video & Media", app: "twitch" },
  { id: "descript", name: "Descript", description: "Video and podcast editing", category: "Video & Media", app: "descript" },
  { id: "riverside", name: "Riverside", description: "Podcast recording", category: "Video & Media", app: "riverside" },
  { id: "mux", name: "Mux", description: "Video infrastructure", category: "Video & Media", app: "mux" },

  // Automation
  { id: "zapier", name: "Zapier", description: "Workflow automation", category: "Automation", app: "zapier" },
  { id: "make", name: "Make (Integromat)", description: "Visual automation", category: "Automation", app: "make" },
  { id: "n8n", name: "n8n", description: "Open-source automation", category: "Automation", app: "n8n" },
  { id: "ifttt", name: "IFTTT", description: "Simple automation", category: "Automation", app: "ifttt" },
  { id: "pipedream", name: "Pipedream", description: "Developer automation", category: "Automation", app: "pipedream" },
  { id: "power-automate", name: "Power Automate", description: "Microsoft automation", category: "Automation", app: "powerautomate" },
  { id: "tray-io", name: "Tray.io", description: "General automation", category: "Automation", app: "trayio" },
  { id: "workato", name: "Workato", description: "Enterprise automation", category: "Automation", app: "workato" },

  // Other
  { id: "google-maps", name: "Google Maps", description: "Maps and geolocation", category: "Other", app: "googlemaps" },
  { id: "weather-api", name: "Weather API", description: "Weather data service", category: "Other", app: "weatherapi" },
  { id: "giphy", name: "Giphy", description: "GIF search and sharing", category: "Other", app: "giphy" },
  { id: "unsplash", name: "Unsplash", description: "Free stock photos", category: "Other", app: "unsplash" },
  { id: "pexels", name: "Pexels", description: "Free stock media", category: "Other", app: "pexels" },
  { id: "wolfram", name: "Wolfram Alpha", description: "Computational knowledge", category: "Other", app: "wolframalpha" },
  { id: "cron", name: "Cron", description: "Calendar for teams", category: "Other", app: "cron" },
  { id: "cal-com", name: "Cal.com", description: "Open scheduling infra", category: "Other", app: "calcom" },
  { id: "webflow", name: "Webflow", description: "No-code website builder", category: "Other", app: "webflow" },
  { id: "wordpress", name: "WordPress", description: "Content management system", category: "Other", app: "wordpress" },
  { id: "ghost", name: "Ghost", description: "Publishing platform", category: "Other", app: "ghost" },
  { id: "contentful", name: "Contentful", description: "Headless CMS", category: "Other", app: "contentful" },
  { id: "sanity", name: "Sanity", description: "Structured content platform", category: "Other", app: "sanity" },
  { id: "strapi", name: "Strapi", description: "Open-source headless CMS", category: "Other", app: "strapi" },
  { id: "prismic", name: "Prismic", description: "Headless page builder", category: "Other", app: "prismic" },
  { id: "storyblok", name: "Storyblok", description: "Visual CMS", category: "Other", app: "storyblok" },
  { id: "directus", name: "Directus", description: "Open data platform", category: "Other", app: "directus" },
  { id: "algolia", name: "Algolia", description: "Search and discovery API", category: "Other", app: "algolia" },
  { id: "twitch-ext", name: "Twitch Extensions", description: "Interactive overlays", category: "Other", app: "twitchextensions" },
  { id: "product-hunt", name: "Product Hunt", description: "Product discovery", category: "Other", app: "producthunt" },
];
