import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { generateBuilderSchema, uploadArtifact } from "./aiSchema";
import { pdfToBlob, palette } from "./pdfBase";
import type { BuilderResult, ReportSchema } from "./types";

const styles = StyleSheet.create({
  page: { padding: 48, fontFamily: "Helvetica", color: palette.body, fontSize: 11, lineHeight: 1.55, backgroundColor: "#fff" },
  cover: { padding: 48, backgroundColor: palette.bgSoft, height: "100%", justifyContent: "center" },
  coverTitle: { fontSize: 32, fontWeight: 700, color: palette.ink, marginBottom: 12 },
  coverMeta: { fontSize: 10, color: palette.muted, marginBottom: 20 },
  exec: { fontSize: 12, color: palette.body, marginBottom: 24, lineHeight: 1.6 },
  kpiRow: { flexDirection: "row", gap: 12, marginTop: 18 },
  kpiCard: { flex: 1, padding: 16, backgroundColor: "#fff", borderRadius: 12, borderWidth: 1, borderColor: palette.line },
  kpiLabel: { fontSize: 9, color: palette.muted, textTransform: "uppercase", letterSpacing: 1, marginBottom: 6 },
  kpiValue: { fontSize: 22, fontWeight: 700, color: palette.ink },
  kpiDelta: { fontSize: 9, color: "#16a34a", marginTop: 4 },
  h2: { fontSize: 18, fontWeight: 700, color: palette.ink, marginTop: 16, marginBottom: 8 },
  body: { fontSize: 11, color: palette.body, marginBottom: 8, textAlign: "justify" },
  chart: { marginTop: 12, padding: 14, borderRadius: 10, backgroundColor: palette.bgSoft, borderWidth: 1, borderColor: palette.line },
  chartTitle: { fontSize: 10, fontWeight: 700, color: palette.ink, marginBottom: 10 },
  bar: { backgroundColor: palette.primary, borderRadius: 3, marginRight: 6 },
  barLabel: { fontSize: 8, color: palette.muted, marginTop: 4 },
});

export async function buildReport(topic: string, brief?: unknown): Promise<BuilderResult> {
  const schema = await generateBuilderSchema<ReportSchema>("report", topic, { brief });
  if (!schema) return { title: topic, summary: "Report generation failed. Please try again." };

  const renderChart = (chart: NonNullable<ReportSchema["sections"]>[number]["chart"]) => {
    if (!chart || !chart.data?.length) return null;
    const max = Math.max(...chart.data.map(d => d.value), 1);
    return (
      <View style={styles.chart} wrap={false}>
        {chart.title ? <Text style={styles.chartTitle}>{chart.title}</Text> : null}
        <View style={{ flexDirection: "row", alignItems: "flex-end", height: 120 }}>
          {chart.data.slice(0, 8).map((d, i) => (
            <View key={i} style={{ flex: 1, alignItems: "center" }}>
              <View style={[styles.bar, { width: "70%", height: (d.value / max) * 110 }]} />
              <Text style={styles.barLabel}>{String(d.name).slice(0, 10)}</Text>
            </View>
          ))}
        </View>
      </View>
    );
  };

  const doc = (
    <Document>
      <Page size="A4" style={styles.cover}>
        <Text style={styles.coverTitle}>{schema.title}</Text>
        <Text style={styles.coverMeta}>Analytical Report · Generated by Megsy</Text>
        {schema.executive_summary ? <Text style={styles.exec}>{schema.executive_summary}</Text> : null}
        {schema.kpis?.length ? (
          <View style={styles.kpiRow}>
            {schema.kpis.slice(0, 4).map((k, i) => (
              <View key={i} style={styles.kpiCard}>
                <Text style={styles.kpiLabel}>{k.label}</Text>
                <Text style={styles.kpiValue}>{String(k.value)}</Text>
                {k.delta ? <Text style={styles.kpiDelta}>{k.delta}</Text> : null}
              </View>
            ))}
          </View>
        ) : null}
      </Page>
      {(schema.sections || []).map((s, i) => (
        <Page key={i} size="A4" style={styles.page}>
          <Text style={styles.h2}>{s.heading}</Text>
          <Text style={styles.body}>{s.body}</Text>
          {renderChart(s.chart)}
        </Page>
      ))}
    </Document>
  );

  const blob = await pdfToBlob(doc);
  const safe = (schema.title || "report").replace(/[^a-z0-9-_ ]/gi, "_").slice(0, 50);
  const url = await uploadArtifact(blob, `${safe}.pdf`);
  const pdfPreviewUrl = URL.createObjectURL(blob);

  return {
    title: schema.title,
    summary: `Your report "${schema.title}" is ready (${schema.sections?.length ?? 0} sections, ${schema.kpis?.length ?? 0} KPIs).`,
    downloadUrl: url ?? undefined,
    pdfPreviewUrl,
    mimeType: "application/pdf",
  };
}
