
-- Update models_added with 15 best fal.ai models (10 image + 5 video)
UPDATE memories SET value = '[
  {"id":"nano-banana-2","name":"Nano Banana 2","type":"image","credits":4,"description":"Ultra-fast generation with vibrant colors and strong text rendering.","longDescription":"Nano Banana 2 delivers exceptional speed with creative compositions and accurate text in images.","icon":"Sparkles","modes":["text-to-image"],"acceptsImages":false,"requiresImage":false,"maxImages":0,"acceptedMimeTypes":[],"provider":"fal.ai","speed":"fast","quality":"high"},
  {"id":"flux-kontext","name":"FLUX Kontext Max","type":"image","credits":5,"description":"Context-aware generation with character and style consistency.","longDescription":"FLUX Kontext Max maintains character identity and style across generations for consistent creative output.","icon":"Layers","modes":["text-to-image"],"acceptsImages":false,"requiresImage":false,"maxImages":0,"acceptedMimeTypes":[],"provider":"BFL","speed":"standard","quality":"ultra"},
  {"id":"ideogram-3","name":"Ideogram 3","type":"image","credits":4,"description":"Best-in-class text rendering within images and creative typography.","longDescription":"Ideogram 3 excels at rendering readable text inside generated images with exceptional typographic accuracy.","icon":"Type","modes":["text-to-image"],"acceptsImages":false,"requiresImage":false,"maxImages":0,"acceptedMimeTypes":[],"provider":"Ideogram","speed":"standard","quality":"high"},
  {"id":"gpt-image","name":"GPT Image 1.5","type":"image","credits":5,"description":"OpenAI photorealistic output with precise prompt adherence.","longDescription":"OpenAI GPT Image 1.5 delivers photorealistic images with exceptional prompt following and detail.","icon":"Image","modes":["text-to-image"],"acceptsImages":false,"requiresImage":false,"maxImages":0,"acceptedMimeTypes":[],"provider":"OpenAI","speed":"standard","quality":"ultra"},
  {"id":"recraft-v4","name":"Recraft V4","type":"image","credits":4,"description":"Professional-grade design for illustrations, icons, and branding.","longDescription":"Recraft V4 specializes in professional design output perfect for branding, illustration, and icon creation.","icon":"PenTool","modes":["text-to-image"],"acceptsImages":false,"requiresImage":false,"maxImages":0,"acceptedMimeTypes":[],"provider":"Recraft","speed":"standard","quality":"high"},
  {"id":"flux-2-pro","name":"FLUX 2 Pro","type":"image","credits":5,"description":"Premium generation with exceptional detail and photorealism.","longDescription":"FLUX 2 Pro delivers top-tier photorealistic output with remarkable detail and composition control.","icon":"Star","modes":["text-to-image"],"acceptsImages":false,"requiresImage":false,"maxImages":0,"acceptedMimeTypes":[],"provider":"BFL","speed":"standard","quality":"ultra"},
  {"id":"seedream-4","name":"Seedream 4.5","type":"image","credits":3,"description":"Balanced model with great quality-to-speed ratio.","longDescription":"ByteDance Seedream 4.5 offers an excellent balance between generation speed and output quality.","icon":"Flower2","modes":["text-to-image"],"acceptsImages":false,"requiresImage":false,"maxImages":0,"acceptedMimeTypes":[],"provider":"ByteDance","speed":"fast","quality":"high"},
  {"id":"grok-imagine","name":"Grok Imagine","type":"image","credits":3,"description":"Creative image generation with unique artistic interpretations.","longDescription":"xAI Grok Imagine creates unique artistic images with creative and sometimes unexpected interpretations.","icon":"Zap","modes":["text-to-image"],"acceptsImages":false,"requiresImage":false,"maxImages":0,"acceptedMimeTypes":[],"provider":"xAI","speed":"standard","quality":"high"},
  {"id":"fal-flux-realism","name":"FLUX Realism","type":"image","credits":3,"description":"Hyper-realistic generation focused on photographic quality.","longDescription":"FLUX Realism is optimized for photorealistic output that closely mimics real photography.","icon":"Camera","modes":["text-to-image"],"acceptsImages":false,"requiresImage":false,"maxImages":0,"acceptedMimeTypes":[],"provider":"BFL","speed":"fast","quality":"high"},
  {"id":"seedream-5-lite","name":"Seedream 5 Lite","type":"image","credits":3,"description":"Lightweight yet powerful model for fast, high-quality generations.","longDescription":"ByteDance Seedream 5 Lite provides fast generation with surprisingly high quality for its speed tier.","icon":"Leaf","modes":["text-to-image"],"acceptsImages":false,"requiresImage":false,"maxImages":0,"acceptedMimeTypes":[],"provider":"ByteDance","speed":"fast","quality":"high"},
  {"id":"kling-3-pro","name":"Kling 3.0 Pro","type":"video","credits":20,"description":"Professional-grade video with excellent character consistency.","longDescription":"Kling 3.0 Pro creates cinematic videos with smooth motion and consistent character rendering.","icon":"Film","modes":["text-to-video"],"acceptsImages":false,"requiresImage":false,"maxImages":0,"acceptedMimeTypes":[],"provider":"Kuaishou","speed":"slow","quality":"ultra"},
  {"id":"veo-3.1-fast","name":"Veo 3.1 Fast","type":"video","credits":12,"description":"Google fastest high-quality video generation.","longDescription":"Veo 3.1 Fast delivers Google-quality video generation at significantly reduced generation times.","icon":"Gauge","modes":["text-to-video"],"acceptsImages":false,"requiresImage":false,"maxImages":0,"acceptedMimeTypes":[],"provider":"Google","speed":"fast","quality":"ultra"},
  {"id":"pika-2.2","name":"Pika 2.2","type":"video","credits":8,"description":"Creative video generation with unique visual effects.","longDescription":"Pika 2.2 creates visually striking videos with creative motion effects and artistic flair.","icon":"Sparkles","modes":["text-to-video"],"acceptsImages":false,"requiresImage":false,"maxImages":0,"acceptedMimeTypes":[],"provider":"Pika","speed":"standard","quality":"high"},
  {"id":"luma-dream","name":"Luma Dream Machine","type":"video","credits":8,"description":"Dream-like video sequences with smooth transitions.","longDescription":"Luma Dream Machine generates flowing, dream-like video sequences with natural motion dynamics.","icon":"Moon","modes":["text-to-video"],"acceptsImages":false,"requiresImage":false,"maxImages":0,"acceptedMimeTypes":[],"provider":"Luma","speed":"standard","quality":"high"},
  {"id":"seedance-pro","name":"Seedance Pro","type":"video","credits":5,"description":"Dance and motion-focused video generation.","longDescription":"ByteDance Seedance Pro specializes in human motion and dance-focused video generation.","icon":"Music","modes":["text-to-video"],"acceptsImages":false,"requiresImage":false,"maxImages":0,"acceptedMimeTypes":[],"provider":"ByteDance","speed":"standard","quality":"high"}
]' WHERE key = 'models_added';
